package com.example.childPortal.model;

public enum HelpType {
    FOOD_ASSISTANCE,
    EDUCATION_SUPPORT,
    MEDICAL_HELP,
    SHELTER,
    CLOTHING,
    COUNSELING,
    LEGAL_PROTECTION,
    LIVELIHOOD_EMPLOYMENT,
    DISABILITY_SUPPORT,
    EMERGENCY_DISASTER,
    OTHER
}