spring.data.mongodb.uri=mongodb://childAdmin:wws3ZWPejVNXXyhe@ac-4eizrxs-shard-00-00.epricby.mongodb.net:27017,ac-4eizrxs-shard-00-01.epricby.mongodb.net:27017,ac-4eizrxs-shard-00-02.epricby.mongodb.net:27017/childPortal?authSource=admin&replicaSet=atlas-h4icqc-shard-0&ssl=true
spring.data.mongodb.database=childPortal
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.option.connections-per-host=10
spring.data.mongodb.option.min-connections-per-host=2

server.port=8080

jwt.secret=U2VjdXJlSldUU2VjcmV0S2V5Rm9yQ2hpbGRQb3J0YWxBcHBsaWNhdGlvbjIwMjQ=
jwt.expiration=86400000

spring.application.name=child-portal

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.email.from=no-reply@childportal.gov.in
app.url=http://localhost:5173