spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://nilakshi2013_db_user:ZVkUs3mOwGhT7jUH@child-protection-portal.s3oylny.mongodb.net/?appName=child-protection-portal
spring.data.mongodb.database=childPortal

server.port=8080


jwt.secret=U2VjdXJlSldUU2VjcmV0S2V5Rm9yQ2hpbGRQb3J0YWxBcHBsaWNhdGlvbjIwMjQ=
jwt.expiration=86400000

spring.application.name=child-portal

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB